// features/admin — khu vực quản trị mức MVP (quyết định owner #14).
// Mọi import từ bên ngoài PHẢI qua file này (boundaries/entry-point).

export { ADMIN_REASON_MIN_LENGTH, isReasonValid, isHexColor } from "./api";

export {
  adminKeys,
  useAdminSystemStatus,
  useAdminColorCharts,
  useAdminColorChart,
  useCreateColorChart,
  useUpdateColorChart,
  useReplaceChartPoints,
  usePublishColorChart,
  useAdminPhBands,
  useUpdatePhBand,
  useAdminCareTips,
  useCreateCareTip,
  useUpdateCareTip,
  useSubmitCareTipReview,
  usePublishCareTip,
  useArchiveCareTip,
  useAdminDataInventory,
  useAdminConsentPurposes,
  useAdminCommunityReports,
  useModerateCommunityReport,
  useAdminActivationCodes,
  useAdminActivationBatches,
  useIssueActivationBatch,
  useVoidActivationCode,
  useVoidActivationBatch,
  useDownloadActivationBatchCsv,
  useAdminPackagePlans,
  useUpdateAdminPackagePlan,
  useAdminProducts,
  useCreateAdminProduct,
  useUpdateAdminProduct,
  useSetAdminProductStatus,
  useAdminJobRuns,
  useAdminOutbox,
  useAdminAuditLogs,
  useAdminMetrics,
  useAdminPrivacyRequests,
  useAdminPrivacyRequest,
  useCreateAdminPrivacyRequest,
  useTransitionAdminPrivacyRequest,
  useAdminRetentionPolicies,
  useDryRunAdminRetentionPolicy,
  useUpdateAdminRetentionPolicy,
  useAdminUsers,
  useLockAdminUser,
  useUnlockAdminUser,
  useAdminUserDetail,
  useUnmaskAdminUser,
  useAdminUserSessions,
  useRevokeAdminUserSessions,
  useAdminMfaResetRequests,
  useRequestAdminMfaReset,
  useApproveAdminMfaReset,
  useGrantAdminRole,
  useRevokeAdminRole,
  useUpdateAdminMaintenance,
} from "./hooks";

export {
  AdminPageHeader,
  AdminSection,
  AdminTableScroll,
  AdminSelect,
  ReasonField,
  ApiErrorNote,
  SavedNote,
  Pager,
  MissingApiNotice,
  adminTableClass,
  adminThClass,
  adminTdClass,
} from "./components";
export type { MissingApiEndpoint, MissingApiNoticeProps } from "./components";

export { validateProductForm, emptyProductForm, formatProductVnd, productToForm, formToPayload } from "./productForm";
export type { ProductFormValues, ProductFormErrors } from "./productForm";

export {
  SHOP_PRODUCT_STATUSES,
  CHART_STATUSES,
  PRODUCT_LINES,
  CARE_TIP_STATUSES,
  CARE_TIP_KINDS,
  CARE_TIP_CATEGORIES,
  CLAIM_TYPES,
} from "./types";

export type {
  AdminOffsetPage,
  PrivacyPage,
  ChartStatus,
  ProductLine,
  ColorChartSummary,
  ColorChartPoint,
  ColorChartDetail,
  CreateColorChartPayload,
  UpdateColorChartPayload,
  ColorChartPointInput,
  UpdatePhBandPayload,
  CareTipStatus,
  CareTipKind,
  CareTipCategory,
  ClaimType,
  CareTipDetail,
  CreateCareTipPayload,
  UpdateCareTipPayload,
  AdminSystemStatus,
  DataInventoryItem,
  ConsentPurposeItem,
  CommunityReport,
  CommunityReportAction,
  ActivationCodeStatus,
  ActivationCodeAdmin,
  ActivationBatch,
  IssueActivationBatchPayload,
  IssuedActivationBatch,
  AdminPlanFeatures,
  AdminPackagePlan,
  AdminProduct,
  AdminProductPayload,
  AdminProductStatus,
  UpdateAdminPackagePlanPayload,
  AdminJobRun,
  AdminOutboxEntry,
  AdminAuditLog,
  AdminMetrics,
  AdminDsarRequest,
  AdminUserStatus,
  AdminUserSummary,
  AdminUserDetail,
  AdminUnmaskResponse,
  AdminSessionItem,
  AdminSessionListResponse,
  AdminMfaResetRequest,
  AdminMaintenance,
  AdminRetentionPolicy,
  AdminRetentionDryRun,
  RetentionAction,
} from "./types";
