-- One row per purpose from p15 section 15.3.2. Optional purposes are never preselected.
INSERT INTO consent_purpose (
    code, label_vi, description_vi, is_mandatory, is_sensitive_data,
    default_state, phase, display_order, active, withdraw_effect
) VALUES
    ('SERVICE_CORE',
     'Cung cấp dịch vụ CatCheck',
     'Xử lý dữ liệu tài khoản và hồ sơ mèo để cung cấp dịch vụ CatCheck.',
     true, false, false, 1, 10, true,
     'Không thể tiếp tục sử dụng dịch vụ cốt lõi.'),
    ('SCAN_IMAGE_RETAIN',
     'Lưu ảnh quét trong 14 ngày',
     'Lưu ảnh bạn chụp tối đa 14 ngày để xem lại và đối chiếu kết quả.',
     false, true, false, 1, 20, true,
     'Ảnh mới bị xoá sau khi trả kết quả; số liệu vẫn được lưu.'),
    ('ALGO_IMPROVEMENT',
     'Cải thiện thuật toán nhận diện màu',
     'Dùng ảnh đã khử nhận dạng để cải thiện thuật toán nhận diện màu.',
     false, true, false, 1, 30, true,
     'Không dùng ảnh mới cho mục đích cải thiện thuật toán.'),
    ('HEALTH_REMINDER_PUSH',
     'Thông báo đẩy nhắc theo dõi',
     'Gửi thông báo đẩy nhắc bạn theo dõi khay cát.',
     false, false, false, 1, 40, true,
     'Không gửi thông báo đẩy nhắc theo dõi.'),
    ('HEALTH_REMINDER_EMAIL',
     'Email nhắc theo dõi',
     'Gửi email nhắc bạn theo dõi khay cát.',
     false, false, false, 1, 50, true,
     'Không gửi email nhắc theo dõi.'),
    ('MARKETING_EMAIL',
     'Email giới thiệu và khuyến mãi',
     'Nhận email giới thiệu sản phẩm, khuyến mãi và kiến thức chăm mèo, tối đa 4 email mỗi tháng.',
     false, false, false, 1, 60, true,
     'Dừng gửi email giới thiệu và khuyến mãi.'),
    ('MARKETING_PUSH',
     'Thông báo đẩy về sản phẩm',
     'Nhận thông báo đẩy về khuyến mãi và sản phẩm mới.',
     false, false, false, 1, 70, true,
     'Dừng gửi thông báo đẩy về sản phẩm.'),
    ('PRODUCT_ANALYTICS',
     'Đo lường để cải thiện sản phẩm',
     'Ghi nhận hành vi sử dụng để cải thiện sản phẩm.',
     false, true, false, 1, 80, true,
     'Dừng thu thập dữ liệu đo lường không thiết yếu.'),
    ('COOKIE_ANALYTICS',
     'Cookie đo lường',
     'Cho phép cookie đo lường không thiết yếu.',
     false, false, false, 1, 90, true,
     'Xoá và không đặt thêm cookie đo lường.'),
    ('LOCATION_MAP',
     'Vị trí để tìm cơ sở thú y',
     'Dùng vị trí hiện tại để tìm cơ sở thú y gần nhất.',
     false, true, false, 2, 100, true,
     'Không dùng vị trí; bạn vẫn có thể nhập địa chỉ.'),
    ('COMMUNITY_PUBLIC',
     'Công khai nội dung cộng đồng',
     'Công khai tên hiển thị, ảnh đại diện và nội dung bạn đăng trong khu vực cộng đồng.',
     false, false, false, 2, 110, true,
     'Không thể đăng nội dung cộng đồng mới.'),
    ('ORDER_FULFILLMENT',
     'Xử lý và giao đơn hàng',
     'Xử lý đơn hàng và chuyển thông tin giao hàng cho đơn vị vận chuyển.',
     true, true, false, 3, 120, true,
     'Không thể đặt đơn hàng mới.')
ON CONFLICT (code) DO UPDATE SET
    label_vi = EXCLUDED.label_vi,
    description_vi = EXCLUDED.description_vi,
    is_mandatory = EXCLUDED.is_mandatory,
    is_sensitive_data = EXCLUDED.is_sensitive_data,
    default_state = EXCLUDED.default_state,
    phase = EXCLUDED.phase,
    display_order = EXCLUDED.display_order,
    active = EXCLUDED.active,
    withdraw_effect = EXCLUDED.withdraw_effect;
