/**
 * Hằng số đường dẫn cho TOÀN BỘ 80 route (p9 §9.4.3, đã hoà giải, THẮNG p19 — xem
 * ghi chú "80 route" trong báo cáo M0). KHÔNG hardcode literal path ở nơi khác —
 * luôn import từ đây.
 *
 * Route có :param giữ nguyên cú pháp react-router (dùng trực tiếp làm `path` trong
 * router.tsx, hoặc generatePath()/Link để build URL thật khi cần).
 */
export const ROUTE_PATTERNS = {
  home: "/",
  login: "/auth/login",
  register: "/auth/register",
  verifyOtp: "/auth/verify-otp",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  oAuthComplete: "/auth/oauth/complete",
  terms: "/legal/terms",
  privacy: "/legal/privacy",
  medicalDisclaimer: "/legal/medical-disclaimer",
  cookies: "/legal/cookies",
  dataRequests: "/legal/data-requests",
  contact: "/legal/contact",
  complaints: "/legal/complaints",
  policyVersions: "/legal/:policyCode/versions",
  policyVersionDetail: "/legal/:policyCode/v/:version",
  onboardingCat: "/onboarding/cat",
  onboardingHealthSurvey: "/onboarding/health-survey",
  onboardingDisclaimer: "/onboarding/disclaimer",
  onboardingActivate: "/onboarding/activate",
  onboardingSuccess: "/onboarding/success",
  dashboard: "/dashboard",
  assistant: "/assistant",
  selectCat: "/scan/select-cat",
  scan: "/scan",
  scanResult: "/scan/result/:scanId",
  scanReassignCat: "/scan/:scanId/reassign-cat",
  catsList: "/cats",
  catNew: "/cats/new",
  catDetail: "/cats/:catId",
  catEdit: "/cats/:catId/edit",
  catHistory: "/cats/:catId/history",
  catTrends: "/cats/:catId/trends",
  scanDetail: "/scans/:scanId",
  sharedTrayLog: "/shared-tray-log",
  historyRedirect: "/history",
  remindersList: "/reminders",
  reminderNew: "/reminders/new",
  reminderDetail: "/reminders/:reminderId",
  export: "/export",
  exportJob: "/export/:jobId",
  credits: "/credits",
  creditsActivate: "/credits/activate",
  notifications: "/notifications",
  settings: "/settings",
  settingsProfile: "/settings/profile",
  settingsSecurity: "/settings/security",
  settingsNotifications: "/settings/notifications",
  settingsLanguage: "/settings/language",
  accountPrivacy: "/account/privacy",
  install: "/install",
  adminDashboard: "/admin",
  adminUsers: "/admin/users",
  adminUserDetail: "/admin/users/:userId",
  adminActivationCodes: "/admin/activation-codes",
  adminPackages: "/admin/packages",
  adminPhColorChart: "/admin/ph-color-chart",
  adminContent: "/admin/content",
  adminPrivacyRequests: "/admin/privacy/requests",
  adminPrivacyRetention: "/admin/privacy/retention",
  adminPlaces: "/admin/places",
  adminCommunityReports: "/admin/community/reports",
  adminSetup2fa: "/admin/setup-2fa",
  adminMeSecurity: "/admin/me/security",
  adminStaff: "/admin/staff",
  adminBroadcast: "/admin/system/broadcast",
  adminJobs: "/admin/system/jobs",
  adminNotificationsOutbox: "/admin/notifications/outbox",
  adminAuditLog: "/admin/audit-log",
  community: "/community",
  communityNew: "/community/new",
  communityPosts: "/community/posts/:postId",
  map: "/map",
  mapClinics: "/map/clinics/:clinicId",
  shop: "/shop",
  shopProducts: "/shop/products/:productId",
  cart: "/cart",
  checkout: "/checkout",
  orders: "/orders/:orderId",
  offline: "/offline",
  notFound: "*",
} as const;

export type RouteKey = keyof typeof ROUTE_PATTERNS;
